language: cpp

compiler:
  - gcc
  
  
addons: 
  apt: 
     - sources: llvm-toolchain-precise-3.6"
     - packages: gcc-6
  
os: 
  - linux
  
dist: xenial

script:
  - g++ --version
  - make test
  - ./bin/test_smart_enum
